### ISSUE TITLE
Weired error on internet explorer 10

### ISSUE THREAD

**Issue by gasserol** [720kb/angular-socialshare#208]
Hello, your code works on every browser, including internet explorer 11 and edge but produces the following error loading module (ONLY on internet explorer 10). Any idea on how to resolve this?

```
SCRIPT1012: '/' erwartet 
angular-socialshare.js, Zeile 20 Zeichen 102
HTML1500: Die Markierung kann nicht selbstschlieﬂend sein. Verwenden Sie eine explizite schlieﬂende Markierung. 
webapp3.ticino-webfactory.ch, Zeile 36 Zeichen 29
HTML1500: Die Markierung kann nicht selbstschlieﬂend sein. Verwenden Sie eine explizite schlieﬂende Markierung. 
webapp3.ticino-webfactory.ch, Zeile 37 Zeichen 29
HTML1500: Die Markierung kann nicht selbstschlieﬂend sein. Verwenden Sie eine explizite schlieﬂende Markierung. 
webapp3.ticino-webfactory.ch, Zeile 38 Zeichen 29
HTML1500: Die Markierung kann nicht selbstschlieﬂend sein. Verwenden Sie eine explizite schlieﬂende Markierung. 
webapp3.ticino-webfactory.ch, Zeile 39 Zeichen 29
HTML1500: Die Markierung kann nicht selbstschlieﬂend sein. Verwenden Sie eine explizite schlieﬂende Markierung. 
webapp3.ticino-webfactory.ch, Zeile 41 Zeichen 25
SCRIPT5022: [$injector:modulerr] Failed to instantiate module application due to:
Error: [$injector:modulerr] Failed to instantiate module 720kb.socialshare due to:
Error: [$injector:nomod] Module '720kb.socialshare' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.12/$injector/nomod?p0=720kb.socialshare
   at Anonymous function (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:7300:11)
   at ensure (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:7224:5)
   at module (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:7298:7)
   at Anonymous function (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9760:11)
   at forEach (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:5619:11)
   at loadModules (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9744:5)
   at Anonymous function (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9761:11)
   at forEach (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:5619:11)
   at loadModules (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9744:5)
   at createInjector (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9669:3)
http://errors.angularjs.org/1.4.12/$injector/modulerr?p0=720kb.socialshare&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'720kb.socialshare'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.12%2F%24injector%2Fnomod%3Fp0%3D720kb.socialshare%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A7300%3A11)%0A%20%20%20at%20ensure%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A7224%3A5)%0A%20%20%20at%20module%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A7298%3A7)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9760%3A11)%0A%20%20%20at%20forEach%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A5619%3A11)%0A%20%20%20at%20loadModules%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9744%3A5)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9761%3A11)%0A%20%20%20at%20forEach%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A5619%3A11)%0A%20%20%20at%20loadModules%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9744%3A5)%0A%20%20%20at%20createInjector%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9669%3A3)
   at Anonymous function (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9783:9)
   at forEach (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:5619:11)
   at loadModules (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9744:5)
   at Anonymous function (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9761:11)
   at forEach (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:5619:11)
   at loadModules (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9744:5)
   at createInjector (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:9669:3)
   at doBootstrap (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:6971:5)
   at bootstrap (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:6992:5)
   at angularInit (http://webapp3.ticino-webfactory.ch/assets/js/foundation.js:6886:5)
http://errors.angularjs.org/1.4.12/$injector/modulerr?p0=application&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20720kb.socialshare%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'720kb.socialshare'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.12%2F%24injector%2Fnomod%3Fp0%3D720kb.socialshare%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A7300%3A11)%0A%20%20%20at%20ensure%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A7224%3A5)%0A%20%20%20at%20module%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A7298%3A7)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9760%3A11)%0A%20%20%20at%20forEach%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A5619%3A11)%0A%20%20%20at%20loadModules%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9744%3A5)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9761%3A11)%0A%20%20%20at%20forEach%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A5619%3A11)%0A%20%20%20at%20loadModules%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9744%3A5)%0A%20%20%20at%20createInjector%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9669%3A3)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.12%2F%24injector%2Fmodulerr%3Fp0%3D720kb.socialshare%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'720kb.socialshare'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.4.12%252F%2524injector%252Fnomod%253Fp0%253D720kb.socialshare%250A%2520%2520%2520at%2520Anonymous%2520function%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A7300%253A11)%250A%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A7224%253A5)%250A%2520%2520%2520at%2520module%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A7298%253A7)%250A%2520%2520%2520at%2520Anonymous%2520function%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A9760%253A11)%250A%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A5619%253A11)%250A%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A9744%253A5)%250A%2520%2520%2520at%2520Anonymous%2520function%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A9761%253A11)%250A%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A5619%253A11)%250A%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A9744%253A5)%250A%2520%2520%2520at%2520createInjector%2520(http%253A%252F%252Fwebapp3.ticino-webfactory.ch%252Fassets%252Fjs%252Ffoundation.js%253A9669%253A3)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9783%3A9)%0A%20%20%20at%20forEach%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A5619%3A11)%0A%20%20%20at%20loadModules%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9744%3A5)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9761%3A11)%0A%20%20%20at%20forEach%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A5619%3A11)%0A%20%20%20at%20loadModules%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9744%3A5)%0A%20%20%20at%20createInjector%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A9669%3A3)%0A%20%20%20at%20doBootstrap%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A6971%3A5)%0A%20%20%20at%20bootstrap%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A6992%3A5)%0A%20%20%20at%20angularInit%20(http%3A%2F%2Fwebapp3.ticino-webfactory.ch%2Fassets%2Fjs%2Ffoundation.js%3A6886%3A5) 
foundation.js, Zeile 9783 Zeichen 9
```
Javascript file is present and it works in all other browsers like safari, chrome, firefox and also on ie11 and edge..

The code of my app.js looks like following:

```
(function() {
  'use strict';

  angular.module('application', [
    'ui.router',
    '720kb.socialshare',
    'ngAnimate',



    //foundation
    'foundation',
    'foundation.dynamicRouting',
    'foundation.dynamicRouting.animations',

  ])

    .controller('OgaSelectorCtrl', OgaSelectorCtrl)
    .controller('ContactController', ContactController)

    .config(config)
    .run(run)
  ;

  config.$inject = ['$urlRouterProvider', '$locationProvider'];

  function config($urlProvider, $locationProvider) {
    $urlProvider.otherwise('/');

    $locationProvider.html5Mode({
      enabled:false,
      requireBase: false
    });

    $locationProvider.hashPrefix('!');

  }

    run.$inject = ['$rootScope', '$location', '$window'];
  function run($rootScope, $location, $window) {
    FastClick.attach(document.body);

      $window.ga('create', 'UA-90022743-1', 'auto');

      // track pageview on state change
      $rootScope.$on('$stateChangeSuccess', function (event) {
          $window.ga('send', 'pageview', $location.path());
      });

  }

  OgaSelectorCtrl.$inject = ['$scope', '$stateParams', '$state', '$controller'];
  function OgaSelectorCtrl($scope, $stateParams, $state, $controller) {
    angular.extend(this, $controller('DefaultController', {$scope: $scope, $stateParams: $stateParams, $state: $state}));


      $scope.clickSwitch = function($scope){
          alert("gogo done1!");
          var ogaswitch1 = document.getElementByClassName('badezimmer-background');
          var string = "url('../images/pics/bad/badezimmer-v3-vio.png')";
          ogaswitch1.setAttribute("style", "background-image: url(" + images[iterator] + ")")

          alert("gogo done2!");
      };

      $scope.install_msg = "Vor der Installation zu klären:";
      $scope.gzw_msg = "Gut zu wissen:";
      $scope.bau_msg = "Bauliche Massnahmen mit Fachperson klären";
      $scope.anbieter_msg = "MONA hat für Sie folgende Anbieter recherchiert:";
      $scope.fachl_msg = "Empfohlene Fachleute und Berater:";

      var page = $state.current.name.split('.')[0];
      $scope.goToAddState = page + ".add";


  }

      ContactController.$inject = ['$scope', '$http'];
      function ContactController($scope, $http) {

      $scope.result = 'hidden'
      $scope.resultMessage;
      $scope.formData; //formData is an object holding the name, email, subject, and message

      $scope.submitButtonDisabled = false;
      $scope.submitted = false; //used so that form errors are shown only after the form has been submitted
      $scope.submit = function(contactform) {
          $scope.submitted = true;
          $scope.submitButtonDisabled = true;
          if (contactform.$valid && $scope.formData!=undefined) {

              var param = function(data) {
                  var returnString = '';
                  for (var d in data){
                      if (data.hasOwnProperty(d))
                          returnString += d + '=' + data[d] + '&';
                  }
                  return returnString.slice( 0, returnString.length - 1 );

              };

              $http({
                  method  : 'POST',
                  url     : 'contact-form.php',
                  data    : param($scope.formData),  //param method from jQuery
                  headers : { 'Content-Type': 'application/x-www-form-urlencoded' }  //set the headers so angular passing info as form data (not request payload)
          }).success(function(data){
                  //console.log(data);

                  if (data.success) { //success comes from the return json object
                      $scope.submitButtonDisabled = true;
                      $scope.resultMessage = data.message;
                      $scope.result='bg-success';

                  } else {
                      $scope.submitButtonDisabled = false;
                      $scope.resultMessage = data.message;
                      $scope.result='bg-danger';

                  }
              });
          } else {
              $scope.submitButtonDisabled = false;
              $scope.resultMessage = 'Failed <img src="http://www.chaosm.net/blog/wp-includes/images/smilies/icon_sad.gif" alt=":(" class="wp-smiley">  Please fill out all the fields.';
              $scope.result='bg-danger';

          }
      }
  }
})();


```

**Comment by 45kb** [comment]
@gasserol Hi this looks quite a weird problem, are you sure you included angular-socialshare.js? 

Also be sure because there is another or some others modules called "socialshare" both on npm and bower if i remember well...

**Comment by gasserol** [comment]
@45kb I implemented the correct angular-socialshare.js and this file is present, just the module is not loading. The proove is: I can share on Facebook, Linkedin, Whatsapp and email, so its working. BUT NOT on Internet Explorer 10. This is the ONLY browser where the module is not loading, on IE11 and EDGE it works, also as on Chrome, Firefox and Safari (all recent versions). If you want to test, see http://webapp3.ticino-webfactory.ch (User and Password on request over private email)

**Comment by 45kb** [comment]
@gasserol could you be so gentle to create a live jsfiddle 
 with your html and js?  
I need to have a look at the entire structure before to say unfortunately.

Also be sure to read around what's going wrong, here something related:
 https://stackoverflow.com/questions/12988506/angularjs-fail-to-load-module 

thanks!

**Comment by gasserol** [comment]
I have read this article, thanks, but this is done correct in my code i believe, as it is working on all other browser.. if that would be wrong, the whole app would not work.

I have to go to meeting, but will prepare you the jsfiddle afterwards. Thanks for your help.

**Comment by 45kb** [comment]
thanks @gasserol ! np

**Comment by gasserol** [comment]
@45kb ok, here is the link to my fiddle, first time using this.

[<https://jsfiddle.net/gasserol/gLgxvog0](url)

**Comment by 45kb** [comment]
@gasserol thanks a lot but... can you fix the 404 errors? I don't know where those files are located actually...

![schermata 2017-06-19 alle 16 44 26](https://user-images.githubusercontent.com/7761650/27290882-dd843abc-550e-11e7-9102-4e891bf9bec2.png)

**Comment by gasserol** [comment]
@45kb I corrected all javascript files in fiddle, css is not relevant as there are not all routes included. by the way, why not looking directly on my server? Everything workes fine there beside the ie10 fenomena. http://webapp3.ticino-webfactory.ch  user mona3 pwd mona2017.. you can load this with ie10 and see console error instead of going through a jsfiddle which is incomplete?

**Comment by 45kb** [comment]
@gasserol oh yes i meant if not possible to enter your server jsfiddle is ok, however ok i am going to try debug it and see what happening, the only problem i have with IE is that i don't use windows at all so debugging from a VM is always terrible 😆  but i'll try my best!

**Comment by 45kb** [comment]
@gasserol SO probably found why is not working, try to include the minified file https://github.com/720kb/angular-socialshare/blob/master/dist/angular-socialshare.min.js 
not the unminified.

Seems like the unminified file has `/*ngInject*` comments and IE is not liking them.

**Comment by gasserol** [comment]
@45kb Filippo in this very moment you are the coolest guy in world :-)))) this is the solution. Many thanks!

**Comment by 45kb** [comment]
@gasserol no problems ahah, thanks to you for spotting this out i'll keep this in mind, actually i don't know if to remove the unminified file from the `dist` folder, usually you should not use unminified files in production.... let's see :)

have a nice day!
